<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PowerSave</RootNamespace>
    <AssemblyName>PowerSave</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <Version>1.0.1</Version>
    <Product>PowerSave Studio</Product>
    <Authors>Vizzy · FSOS Labs</Authors>
    <Company>Vizzy · FSOS Labs</Company>
    <Description>Premium featherweight Windows power-mode switcher — Ultra Power Save, Power Save, Ultra Performance in one click.</Description>
    <Copyright>Copyright © 2026 FSOS Labs</Copyright>
    <AssemblyTitle>PowerSave Studio</AssemblyTitle>
    <RepositoryUrl>https://github.com/bro4cvf-hash/powersave-studio</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/bro4cvf-hash/powersave-studio</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <InvariantGlobalization>true</InvariantGlobalization>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <DebugType>none</DebugType>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

</Project>
